general:
  # Should the plugin check for updates?
  updates:
    check: true
    # Automatically download & install?
    download: false

  # Should the plugin output some useful information when scanning for blocks?
  debug: false

  # Max tiles in a chunk (Default: 256) -1 to disable
  # A chunk is defined as width x length x height blocks (16 x 16 x 256).
  limit: 256

  # Worlds in which the live-tile-scanning feature should be enabled/disabled
  worlds:
    # Blacklist mode = false
    # Whitelist mode = true
    whitelist: true
    list:
      - "world"
      - "world_nether"
      - "world_the_end"

  # Regions in which the live-tile-scanning feature should be enabled/disabled
  regions:
    # Blacklist mode = false
    # Whitelist mode = true
    whitelist: false
    list:
      - "region1"

  # Customize the blocks which may be placed inside regions!
  region_blocks:
    # This will disallow DIAMOND_ORE placements inside region 'region1'
    region1:
      # Blacklist mode = false
      # Whitelist mode = true
      whitelist: false
      list:
        - "DIAMOND_ORE"
    # This will only allow DIAMOND_ORE placements inside region 'region2'
    region2:
      whitelist: true
      list:
        - "DIAMOND_ORE"

  notification:
    # How we inform the player about the live-tile count
    # Possible values are "ACTIONBAR", "BOSSBAR"
    # Default: "BOSSBAR"
    #
    # Please note: bossbar is only on Minecraft versions greater than or equal to 1.9!
    type: "BOSSBAR"

    bossbar:
      # Bossbar color
      # Possible values are "BLUE", "GREEN", "PINK", "PURPLE", "RED", "WHITE", "YELLOW"
      # Default: "BLUE"
      color: "BLUE"

      # Bossbar style
      # Possible values are "SOLID", "SEGMENTED_6", "SEGMENTED_10", "SEGMENTED_12", "SEGMENTED_20"
      # Default: "SEGMENTED_10"
      style: "SEGMENTED_10"

      # Bossbar flags
      # Possible values are "DARKEN_SKY", "PLAY_BOSS_MUSIC", "CREATE_FOG"
      # Default: []
      flags: [] # Remove [] to addCompletableFuture values
      #  - "DARKEN_SKY"
      #  - "PLAY_BOSS_MUSIC"

      # Bossbar duration before it should disappear in ticks
      # 1 second = 20 ticks
      duration: 60

  # Send notification when scanning in actionbar/bossbar
  scan_notification: true

  # If limit is disabled (= -1), should we still show the bossbar/actionbar
  # for tile entities? If set to false, this will still show the bossbar or
  # actionbar for custom defined blocks.
  always_show_notification: true

  # Scanradius default radius (which will appear in tabcomplete)
  # Default: 5
  scanradius_default: 5

  # Set a limit to custom blocks in a chunk
  # Bypass with e.g. 'insights.bypass.DIAMOND_ORE' permission
  materials:
    # Format:
    # MATERIAL: LIMIT
    DIAMOND_ORE: 128
    ENCHANTING_TABLE: 16 # If on < 1.13 use "ENCHANTMENT_TABLE"