[versions]
# libraries
semver = "0.10.2"
minecraft = "1.21.3-R0.1-SNAPSHOT"
paperLib = "1.0.8"
bStats = "3.0.0"
adventure = "4.17.0"
adventurePlatformBukkit = "4.3.3"
assertj = "3.23.1"
mockito = "4.11.0"
jupiter = "5.9.1"
brigadier = "1.0.18"
placeholderapi = "2.11.6"
commodore = "2.2"
cloudPaper = "2.0.0-beta.9"
cloud = "2.0.0-rc.2"

# plugins
shadow = "9.0.0-beta2"
userdev = "1.7.5"
pluginYml = "0.6.0"

[libraries]
semver = { group = "com.github.zafarkhaja", name = "java-semver", version.ref = "semver" }
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "minecraft" }
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
bStatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bStats" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureMiniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventurePlatformBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventurePlatformBukkit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
commodore = { group = "me.lucko", name = "commodore", version.ref = "commodore" }
cloudPaper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloudPaper" }
cloudAnnotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginYml" }
